version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: loizenaidb

    ports:
      - "5432:5432"

  frontend:
    image: sheshuvalandas/frontend
    container_name: frontend
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      proxy: http://127.0.0.1:8080

  backend:
    image: sheshuvalandas/backend
    container_name: backend
    environment:
      database: loizenaidb
      username: postgres
      password: 123
      host: postgres
      dialect: postgres

    ports:
      - "8080:8080"

    #depends_on:
    #  - postgres
