version: "3.9"
services:


  frontend:
    image: sheshuvalandas/frontend
    container_name: frontend
    stdin_open: true
    ports:
      - "3000:3000"
    #links:
    #  - backend
    #command: npm start

  backend:
    image: sheshuvalandas/backend
    container_name: backend
    ports:
      - "8080:8080"

    #depends_on:
    #  - postgres
    #environment:
    #  database: loizenaidb
    #  username: postgres
    #  password: 123
    #  host: postgres
    #command: node server.js
    #env_file:
    #  - /root/backend/app/config/env.js



  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: loizenaidb

    #volumes:
    #  - postgres:/var/lib/postgresql/data
