version: "3.9"
services:


  frontend:
    image: sheshuvalandas/frontend
    container_name: frontend
    stdin_open: true
    ports:
      - "3000:3000"

    depends_on:
      - backend

  backend:
    image: sheshuvalandas/backend
    container_name: backend
    ports:
      - "8080:8080"

    depends_on:
      - postgres
    environment:
      database: loizenaidb
      username: postgres
      password: 123
      host: postgres



  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"

    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: loizenaidb

  #nginx:
  #  depends_on:
  #    - backend
  #    - frontend
  #  restart: always
  #  image: sheshuvalandas/nginx-file
  #  ports:
  #    - "3050:80"
