version: "3.9"
services:


  frontend:
    image: sheshuvalandas/frontend
    container_name: frontend
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /app/frontend/node_modules
      - .:/app/frontend

    ports:
      - "3000:3000"

    #links:
    #  - backend
    #command: npm start

  backend:
    image: sheshuvalandas/backend
    container_name: backend
    ports:
      - "8080:8080"

    volumes:
      - /app/backend/node_modules
      - /root/backend:/app/backend
    depends_on:
      - postgres
    environment:
      database: loizenaidb
      username: postgres
      password: 123
      host: postgres



  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"

    environment:
      POSTGRES_PASSWORD: 123


    #volumes:
    #  - postgres:/var/lib/postgresql/data

  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    image: sheshuvalandas/nginx-file
    ports:
      - "3050:80"
